# Generated by Django 5.1.1 on 2024-09-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_omegacharacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlecharacterquestion',
            name='chinese_word',
            field=models.CharField(max_length=1),
        ),
    ]
