# Generated by Django 5.1.1 on 2024-10-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0005_alter_singlecharacterquestion_chinese_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
